Vagrant.configure("2") do |config|
  config.vm.box      = "generic/ubuntu2204"
  config.vm.hostname = "vm03"

  config.vm.network "private_network", ip: "192.168.56.12"

  config.vm.provider "libvirt" do |vb|
    vb.cpus   = 2
    vb.memory = 4096
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y python3-pip curl

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io
    usermod -aG docker vagrant
  SHELL
end
